In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
headache_df = pd.read_csv('Migrebot_05.09.2026_4efb0a743bd6.csv')
meteo_df = pd.read_csv('open-meteo.csv', skiprows=3)

In [6]:
headache_df.head()

,Дата,Время,Головная боль,Признаки мигрени,Принятые медикаменты,Интенсивность боли,Локализация,Характер,Нагрузки,Тошнота,ФоТофобия,ФоНофобия,Триггеры,Начало боли,Окончание боли,Комментарии,Свой вопрос
0,2026-09-04,21:15,Да,NaN,"Ибупрофен 400, Помогло",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-09-03,21:10,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-09-01,21:51,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Автоматическая запись,NaN
3,2026-08-31,21:19,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Автоматическая запись,NaN
4,2026-08-30,21:32,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
headache_df['Головная боль'].value_counts()

Головная боль
Нет    85
Да     24
Name: count, dtype: int64

In [8]:
headache_df[headache_df['Головная боль'] == 'Да'].head()

,Дата,Время,Головная боль,Признаки мигрени,Принятые медикаменты,Интенсивность боли,Локализация,Характер,Нагрузки,Тошнота,ФоТофобия,ФоНофобия,Триггеры,Начало боли,Окончание боли,Комментарии,Свой вопрос
0,2026-09-04,21:15,Да,NaN,"Ибупрофен 400, Помогло",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2026-08-16,21:08,Да,NaN,Нет,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Автоматическая запись,Нет
16,2026-08-15,21:21,Да,Да,"суматриптан 50 мг, Немного помогло",5.0,Слева,Пульсировала,Да,Да,Да,Да,NaN,Днём,Нет,NaN,NaN
23,2026-08-08,21:08,Да,NaN,"Ибупрофен 400, Помогло",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2026-07-26,21:07,Да,NaN,"Ибупрофен 400, Не помогло",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
meteo_df.head()

,time,temperature_2m_mean (°C),temperature_2m_max (°C),temperature_2m_min (°C),precipitation_sum (mm),precipitation_hours (h),sunshine_duration (s),wind_gusts_10m_max (km/h),relative_humidity_2m_mean (%),relative_humidity_2m_max (%),relative_humidity_2m_min (%),pressure_msl_mean (hPa),pressure_msl_max (hPa),pressure_msl_min (hPa),cloud_cover_mean (%),wind_speed_10m_mean (km/h)
0,2026-05-03,10.1,12.0,8.8,1.6,14.0,952.24,23.8,96,100,88,1013.7,1018.3,1007.8,99,3.6
1,2026-05-04,11.0,13.5,8.6,5.1,8.0,9484.74,28.1,94,100,87,1007.7,1010.6,1005.3,92,5.3
2,2026-05-05,11.8,14.5,8.8,5.6,13.0,15073.64,25.2,93,100,84,1012.7,1015.7,1009.0,84,5.6
3,2026-05-06,12.4,14.5,10.9,4.0,17.0,20115.02,25.2,92,100,80,1018.0,1020.6,1015.4,92,5.4
4,2026-05-07,12.8,16.6,8.4,0.0,0.0,45407.92,22.3,85,95,69,1021.3,1022.2,1020.3,64,3.8